### ISSUE TITLE
Chat window doesn't scroll to the bottom automatically

### ISSUE THREAD

**Issue by benji011** [benji011/yggdrasil#3]
## What

When you enter a chat room the conversation window doesn't automatically scroll and start from the bottom

## Why

So users can see the latest /recent message

![image](https://user-images.githubusercontent.com/6195689/135754208-1349b976-4172-4448-9341-d0d28afdc842.png)

**Comment by jason1985** [comment]
Hi I would like to work on this issue if possible.
Thanks!

**Comment by benji011** [comment]
@jason1985 Thanks! Go for it!

**Comment by benji011** [comment]
Issue closed. Thanks @jason1985 !
