### ISSUE TITLE
Latest messages not toggled when switching chatrooms

### ISSUE THREAD

**Issue by benji011** [benji011/yggdrasil#5]
## What
- From https://github.com/benji011/yggdrasil/pull/4#issuecomment-932980696
- Changing to another chatroom from the menu doesn't toggle the user to the most recent messages at the bottom of the window

## Why
Probably all the chat data isn't loaded in time before the `scrollToBottom` method is called.

## How
There are a few ways you can fix this:

1. The easiest is to delay the time the chat window is loaded by waiting for all messages have been set in state. Or ..
2. You can somehow do some maths and save the height of the chat window in its state and then pass it in as props. This way you can load the chat window instantly while fixing the toggle issue

**Comment by adryan30** [comment]
I can work on this!

**Comment by benji011** [comment]
Thanks @adryan30 ! It's all yours. Let me know if you have any questions!
